result_prefix: 'llama3_collected'
dataset: '../../data/document_folds/collected_acp.csv'
generation:
  model: "meta-llama/Meta-Llama-3-8B"
  checkpoint: "../../checkpoints/generation/collected/checkpoint/"
  device: "cuda:0"
verification:
  enable: False
configs:
  save_detailed_results: True
  folder: 'results'
