result_prefix: 'llama3_ibm'
dataset: '../../data/document_folds/ibm_acp.csv'
generation:
  model: "meta-llama/Meta-Llama-3-8B"
  checkpoint: "../../checkpoints/generation/ibm/checkpoint/"
  device: "cuda:0"
verification:
  enable: False
configs:
  save_detailed_results: True
  folder: 'results'
